export interface MindTreeNode {
  id: string;
  title: string;
  description: string;
  category: string;
  level: 'Beginner' | 'Intermediate' | 'Advanced' | 'Expert';
  estimatedHours: number;
  tools: string[];
  concepts: string[];
  projectIdea: string;
  isPopular?: boolean;
}

export interface MindTreeBranch {
  id: string;
  title: string;
  tagline: string;
  iconName: string;
  phaseNumber: number;
  estimatedWeeks: number;
  nodes: MindTreeNode[];
}

export interface RoadmapMilestone {
  phase: number;
  title: string;
  duration: string;
  level: 'Beginner' | 'Intermediate' | 'Advanced' | 'Capstone' | 'Industry Ready';
  description: string;
  deliverable: string;
  keySkills: string[];
  checkpointProjects: string[];
}

export interface TechRoadmap {
  id: string;
  title: string;
  category: 'web' | 'security' | 'cloud' | 'automation' | 'ai' | 'data';
  categoryLabel: string;
  tagline: string;
  description: string;
  iconName: string;
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
  duration: string;
  weeklyCommitment: string;
  totalTopics: number;
  salaryBenchmark: string;
  badgeColor: string;
  accentGradient: string;
  careerRoles: string[];
  overviewStats: {
    phasesCount: number;
    projectsCount: number;
    estimatedTotalHours: number;
  };
  mindtree: MindTreeBranch[];
  milestones: RoadmapMilestone[];
  relatedCourses: string[];
  relatedTools: string[];
  relatedNotes: string[];
}

export const TECH_ROADMAPS: TechRoadmap[] = [
  // ── 1. FULL-STACK WEB DEVELOPMENT ──────────────────────────────────────────
  {
    id: 'web-development',
    title: 'Full-Stack Web Architect',
    category: 'web',
    categoryLabel: 'Web Development',
    tagline: 'From frontend reactive DOM to high-concurrency microservices, edge computing, and distributed database sharding.',
    description: 'A master curriculum guiding engineers from standard UI scripting into production-grade full-stack architectures. Covers TypeScript, React 19, Next.js 15 App Router, Node.js, Go microservices, PostgreSQL relational modeling, Redis caching, and edge deployment.',
    iconName: 'Globe',
    difficulty: 'Intermediate',
    duration: '6 Months',
    weeklyCommitment: '10-12 hrs/week',
    totalTopics: 28,
    salaryBenchmark: '₹14 LPA - ₹48 LPA / $110k - $190k',
    badgeColor: 'blue',
    accentGradient: 'from-blue-600 via-indigo-600 to-cyan-500',
    careerRoles: ['Senior Frontend Engineer', 'Full-Stack Developer', 'Lead Web Architect', 'Founding Software Engineer'],
    overviewStats: {
      phasesCount: 5,
      projectsCount: 6,
      estimatedTotalHours: 240,
    },
    mindtree: [
      {
        id: 'web-p1',
        title: 'Modern Frontend & Type-Safe UI',
        tagline: 'DOM mechanics, TypeScript strict mode, component life-cycles, and CSS architecture.',
        iconName: 'Layout',
        phaseNumber: 1,
        estimatedWeeks: 4,
        nodes: [
          {
            id: 'web-ts-strict',
            title: 'TypeScript Strict Mode & Generics',
            description: 'Master type narrowing, mapped types, conditional generics, and utility types for bulletproof interfaces.',
            category: 'Language Core',
            level: 'Beginner',
            estimatedHours: 18,
            tools: ['TypeScript 5.x', 'ts-node', 'tsc'],
            concepts: ['Type Narrowing', 'Union & Discriminated Types', 'Generic Constraints', 'Infer Keyword'],
            projectIdea: 'Build a strongly-typed schema validator library with chainable validation rules.',
            isPopular: true,
          },
          {
            id: 'web-react-19',
            title: 'React 19 & Concurrent State',
            description: 'Server actions, optimistic updates, useActionState, useOptimistic, and Suspense boundaries.',
            category: 'Frontend Framework',
            level: 'Intermediate',
            estimatedHours: 25,
            tools: ['React 19', 'Vite', 'React DevTools'],
            concepts: ['Concurrent Rendering', 'Optimistic UI', 'Server Actions', 'Custom Hooks & State Primitives'],
            projectIdea: 'Build an interactive Kanban board with instant drag-and-drop rollbacks on failure.',
            isPopular: true,
          },
          {
            id: 'web-tailwind-design',
            title: 'Modern CSS, Tokens & Glassmorphism',
            description: 'Design token architecture, responsive viewports, CSS Grid subgrids, and modern dark-mode glass styling.',
            category: 'Styling & UX',
            level: 'Beginner',
            estimatedHours: 14,
            tools: ['Tailwind CSS', 'CSS Modules', 'PostCSS'],
            concepts: ['CSS Grid & Flexbox', 'Custom Properties / Tokens', 'Subgrid Layouts', 'Backdrop Filter Effects'],
            projectIdea: 'Craft a high-converting developer SaaS marketing landing page with interactive dark mode.',
          },
        ],
      },
      {
        id: 'web-p2',
        title: 'Server-Side Rendering & Edge Frameworks',
        tagline: 'SSR, SSG, ISR, Streaming HTTP response, and Server Components.',
        iconName: 'Server',
        phaseNumber: 2,
        estimatedWeeks: 5,
        nodes: [
          {
            id: 'web-next-15',
            title: 'Next.js 15 & Hybrid Rendering',
            description: 'Server Components vs Client Components, Route Handlers, Middlewares, and dynamic caching policies.',
            category: 'Full-Stack Framework',
            level: 'Intermediate',
            estimatedHours: 30,
            tools: ['Next.js 15', 'Turbopack', 'Vercel CLI'],
            concepts: ['RSC Tree', 'Streaming SSR', 'Static Generation (SSG)', 'Incremental Static Regeneration (ISR)'],
            projectIdea: 'Build an e-commerce platform with real-time stock sync and instant edge rendering.',
            isPopular: true,
          },
          {
            id: 'web-api-design',
            title: 'REST, GraphQL & tRPC Architectures',
            description: 'Design clean RESTful contracts, type-safe RPC procedures with tRPC, and GraphQL schemas with DataLoader.',
            category: 'API Engineering',
            level: 'Intermediate',
            estimatedHours: 20,
            tools: ['tRPC', 'GraphQL Yoga', 'Zod', 'Postman / Bruno'],
            concepts: ['End-to-End Type Safety', 'Schema Validation', 'N+1 Query Resolution', 'JWT & OAuth2 Bearer Tokens'],
            projectIdea: 'Build an end-to-end API gateway with rate-limiting middleware and schema validation.',
          },
        ],
      },
      {
        id: 'web-p3',
        title: 'Databases, Caching & Relational Modeling',
        tagline: 'ACID transactions, indexing strategies, migrations, and Redis caching layers.',
        iconName: 'Database',
        phaseNumber: 3,
        estimatedWeeks: 5,
        nodes: [
          {
            id: 'web-postgres-modeling',
            title: 'PostgreSQL Relational Modeling & Indexing',
            description: 'Primary/Foreign keys, multi-column B-Tree indexes, EXPLAIN ANALYZE query profiling, and ACID constraints.',
            category: 'Database Core',
            level: 'Intermediate',
            estimatedHours: 24,
            tools: ['PostgreSQL 16', 'pgAdmin / DBeaver', 'Drizzle ORM / Prisma'],
            concepts: ['Index Selection', 'Foreign Key Cascades', 'Query Execution Plans', 'Connection Pooling (PgBouncer)'],
            projectIdea: 'Design a multi-tenant database schema with row-level security (RLS) isolation.',
            isPopular: true,
          },
          {
            id: 'web-redis-caching',
            title: 'Redis Distributed Caching & Queues',
            description: 'In-memory key-value lookups, cache stampede mitigation, TTL policies, and pub/sub message brokers.',
            category: 'Performance',
            level: 'Advanced',
            estimatedHours: 18,
            tools: ['Redis', 'BullMQ', 'ioredis'],
            concepts: ['Cache Aside Pattern', 'Write-Through Caching', 'Pub/Sub Event Bus', 'Distributed Locks'],
            projectIdea: 'Build a background job worker queue that handles email broadcasting and PDF generation.',
          },
        ],
      },
      {
        id: 'web-p4',
        title: 'System Architecture & Production Deployment',
        tagline: 'Docker containerization, CI/CD pipelines, reverse proxies, and cloud delivery.',
        iconName: 'Cloud',
        phaseNumber: 4,
        estimatedWeeks: 6,
        nodes: [
          {
            id: 'web-docker-deploy',
            title: 'Containerization & Multi-Stage Docker',
            description: 'Package full-stack web apps into hardened, minimal Alpine/Distroless Docker images for zero-downtime releases.',
            category: 'DevOps & Infra',
            level: 'Intermediate',
            estimatedHours: 20,
            tools: ['Docker', 'Docker Compose', 'NGINX'],
            concepts: ['Multi-Stage Builds', 'Layer Caching', 'Environment Secrets', 'Reverse Proxy Configuration'],
            projectIdea: 'Dockerize a Next.js + Node + Postgres + Redis application with automated compose orchestration.',
            isPopular: true,
          },
          {
            id: 'web-websockets-realtime',
            title: 'Real-Time WebSockets & SSE',
            description: 'Bidirectional communication protocols, heartbeats, socket rooms, and Server-Sent Events for live dashboards.',
            category: 'Realtime Architecture',
            level: 'Advanced',
            estimatedHours: 18,
            tools: ['Socket.io', 'ws', 'SSE'],
            concepts: ['WebSocket Handshake', 'Room Broadcasting', 'Connection Reconnection Logic', 'Event Streaming'],
            projectIdea: 'Build a real-time collaborative whiteboarding & chat platform with presence detection.',
          },
        ],
      },
      {
        id: 'web-p5',
        title: 'Production Capstone & Interview Readiness',
        tagline: 'Full enterprise SaaS capstone, high-scale system design, and coding interview mastery.',
        iconName: 'Award',
        phaseNumber: 5,
        estimatedWeeks: 4,
        nodes: [
          {
            id: 'web-enterprise-capstone',
            title: 'Enterprise Multi-Tenant SaaS Capstone',
            description: 'Build a complete SaaS platform featuring Stripe billing, team memberships, audit logging, and automated backups.',
            category: 'Capstone & Portfolio',
            level: 'Expert',
            estimatedHours: 40,
            tools: ['Next.js 15', 'PostgreSQL', 'Stripe API', 'Redis', 'Docker'],
            concepts: ['Tenant Isolation', 'Stripe Webhooks', 'Role-Based Access Control', 'Automated Health Monitoring'],
            projectIdea: 'Launch and deploy a production-ready SaaS application with live demo and source code.',
            isPopular: true,
          },
        ],
      },
    ],
    milestones: [
      {
        phase: 1,
        title: 'Frontend Component Engineering',
        duration: 'Month 1',
        level: 'Beginner',
        description: 'Establish foundational proficiency in TypeScript strict typing and modular React component patterns.',
        deliverable: 'A responsive, fully typed dashboard UI with theme switching and dynamic form validation.',
        keySkills: ['TypeScript Generics', 'React 19 Hooks', 'Tailwind CSS', 'Accessible Forms'],
        checkpointProjects: ['Developer Portfolio UI', 'Interactive Financial Calculator'],
      },
      {
        phase: 2,
        title: 'Server-Side & API Frameworks',
        duration: 'Month 2',
        level: 'Intermediate',
        description: 'Master server-side rendering, streaming responses, and designing clean contract-driven REST and RPC APIs.',
        deliverable: 'A full-stack Next.js application backed by typed server actions and JWT session auth.',
        keySkills: ['Next.js 15 App Router', 'Server Components', 'Zod Schema Validation', 'Authentication Protocols'],
        checkpointProjects: ['Course LMS Platform', 'Multi-Author Blog Engine'],
      },
      {
        phase: 3,
        title: 'Database Design & Caching',
        duration: 'Month 3-4',
        level: 'Intermediate',
        description: 'Build robust relational data models in PostgreSQL, optimize query performance, and integrate Redis cache layers.',
        deliverable: 'A high-throughput API with indexed SQL queries, caching layer, and background worker queues.',
        keySkills: ['PostgreSQL Schema Design', 'Query Indexing', 'Redis In-Memory Caching', 'BullMQ Workers'],
        checkpointProjects: ['URL Shortener with Analytics', 'Real-Time Notification Dispatcher'],
      },
      {
        phase: 4,
        title: 'Production Infrastructure & Scaling',
        duration: 'Month 5',
        level: 'Advanced',
        description: 'Containerize with Docker, establish automated GitHub Actions CI/CD pipelines, and configure production reverse proxies.',
        deliverable: 'A containerized microservices stack running on cloud VPS with zero-downtime rollouts.',
        keySkills: ['Docker Multi-Stage', 'CI/CD Pipelines', 'NGINX Reverse Proxy', 'SSL/TLS Handshakes'],
        checkpointProjects: ['Microservices Orchestration Stack'],
      },
      {
        phase: 5,
        title: 'Enterprise Capstone & Career Mastery',
        duration: 'Month 6',
        level: 'Capstone',
        description: 'Architect and deploy an enterprise-grade SaaS platform, accompanied by system design interview preparation.',
        deliverable: 'Live production SaaS deployed on custom domain with monetization, documentation, and automated tests.',
        keySkills: ['System Design at Scale', 'Stripe Billing Webhooks', 'Performance Profiling', 'Technical Interviewing'],
        checkpointProjects: ['Collaborative Cloud Workspace SaaS'],
      },
    ],
    relatedCourses: ['course-1', 'course-2', 'course-5'],
    relatedTools: ['tool-docker-desktop', 'tool-postman', 'tool-vscode'],
    relatedNotes: ['notes-fullstack-dev', 'notes-react-handbook', 'notes-dsa-java'],
  },

  // ── 2. CYBER SECURITY & ETHICAL HACKING ────────────────────────────────────
  {
    id: 'cyber-security',
    title: 'Cyber Security & Offensive / Defensive Specialist',
    category: 'security',
    categoryLabel: 'Cyber Security',
    tagline: 'From Linux internals and network packet analysis to OWASP Top 10 exploits, SOC defensive monitoring, and cloud pentesting.',
    description: 'A comprehensive cybersecurity training track spanning offensive ethical hacking and defensive blue teaming. Master TCP/IP packet dissection with Wireshark, Linux privileges, Web App vulnerabilities (SQLi, XSS, SSRF, IDOR), Burp Suite Pro workflows, Metasploit, SIEM logging with Splunk, and Incident Response.',
    iconName: 'Shield',
    difficulty: 'Intermediate',
    duration: '7 Months',
    weeklyCommitment: '12 hrs/week',
    totalTopics: 32,
    salaryBenchmark: '₹15 LPA - ₹55 LPA / $115k - $210k',
    badgeColor: 'rose',
    accentGradient: 'from-rose-600 via-red-600 to-amber-500',
    careerRoles: ['Ethical Hacker / Pentester', 'SOC Security Analyst (L1/L2)', 'Security Engineer', 'AppSec Specialist'],
    overviewStats: {
      phasesCount: 5,
      projectsCount: 7,
      estimatedTotalHours: 280,
    },
    mindtree: [
      {
        id: 'sec-p1',
        title: 'Core Foundations: Networking & Linux Security',
        tagline: 'OSI layers, packet analysis, shell scripting, and Linux permission hardening.',
        iconName: 'Terminal',
        phaseNumber: 1,
        estimatedWeeks: 5,
        nodes: [
          {
            id: 'sec-networking',
            title: 'Network Protocols & Packet Analysis',
            description: 'Master TCP 3-way handshakes, subnetting, DNS routing, ARP spoofing detection, and packet inspection.',
            category: 'Networking',
            level: 'Beginner',
            estimatedHours: 24,
            tools: ['Wireshark', 'tcpdump', 'nmap', 'netcat'],
            concepts: ['OSI 7 Layers', 'TCP vs UDP', 'ICMP Handshakes', 'Subnet Masking & CIDR'],
            projectIdea: 'Capture and reconstruct an unencrypted HTTP/FTP login session from a PCAP packet trace.',
            isPopular: true,
          },
          {
            id: 'sec-linux-internals',
            title: 'Linux Systems Internals & Hardening',
            description: 'File permissions (chmod, SUID, SGID), process management, cron persistence, and SSH key management.',
            category: 'Operating Systems',
            level: 'Beginner',
            estimatedHours: 20,
            tools: ['Kali Linux', 'Bash', 'Lynis', 'OpenSSH'],
            concepts: ['SUID Privilege Abuse', 'PAM Authentication', 'Firewall Rules (UFW/iptables)', 'Log Inspection (/var/log)'],
            projectIdea: 'Harden a fresh Ubuntu cloud VPS using Lynis security audit benchmark to score 85+ points.',
            isPopular: true,
          },
        ],
      },
      {
        id: 'sec-p2',
        title: 'Web Application Penetration Testing',
        tagline: 'OWASP Top 10, proxy interception, authentication bypasses, and API exploits.',
        iconName: 'Crosshair',
        phaseNumber: 2,
        estimatedWeeks: 6,
        nodes: [
          {
            id: 'sec-burpsuite',
            title: 'Burp Suite & Request Interception',
            description: 'Configure proxy listeners, Repeater inspection, Intruder fuzzing, and custom Burp extensions.',
            category: 'Tooling',
            level: 'Intermediate',
            estimatedHours: 22,
            tools: ['Burp Suite Community / Pro', 'Caido', 'FoxyProxy'],
            concepts: ['HTTP Request/Response Tampering', 'Session Tokens', 'Header Manipulation', 'Intruder Attack Types'],
            projectIdea: 'Solve PortSwigger Web Security Academy practitioner labs for broken access control.',
            isPopular: true,
          },
          {
            id: 'sec-owasp-top-10',
            title: 'OWASP Top 10 Vulnerabilities',
            description: 'Deep dive into SQL Injection (Union, Blind, Time-based), Cross-Site Scripting (Reflected, Stored), IDOR, and SSRF.',
            category: 'Offensive Security',
            level: 'Intermediate',
            estimatedHours: 35,
            tools: ['SQLmap', 'FFUF', 'OWASP ZAP', 'Gobuster'],
            concepts: ['SQL Injection Payloads', 'Stored XSS Filter Evasion', 'Server-Side Request Forgery', 'IDOR Authorization Flaws'],
            projectIdea: 'Discover and write an exploit report for an intentional IDOR & SQLi vulnerability on DVWA.',
            isPopular: true,
          },
          {
            id: 'sec-api-pentesting',
            title: 'REST & GraphQL API Pentesting',
            description: 'BOLA (Broken Object Level Auth), mass assignment, JWT token manipulation, and rate limit evasion.',
            category: 'API Security',
            level: 'Intermediate',
            estimatedHours: 20,
            tools: ['Postman', 'jwt_tool', 'Kiterunner'],
            concepts: ['BOLA / BFLA', 'JWT None Algorithm Flaw', 'Parameter Tampering', 'GraphQL Introspection Exploits'],
            projectIdea: 'Perform a comprehensive API penetration test on an exposed e-commerce backend.',
          },
        ],
      },
      {
        id: 'sec-p3',
        title: 'Network Attacks, Exploitation & Active Directory',
        tagline: 'Vulnerability scanners, Metasploit, privilege escalation, and AD Kerberos attacks.',
        iconName: 'Cpu',
        phaseNumber: 3,
        estimatedWeeks: 6,
        nodes: [
          {
            id: 'sec-metasploit',
            title: 'Metasploit & Exploit Engineering',
            description: 'SearchSploit vulnerability mapping, payload generation with msfvenom, Meterpreter listeners, and pivoting.',
            category: 'Exploitation',
            level: 'Intermediate',
            estimatedHours: 25,
            tools: ['Metasploit Framework', 'msfvenom', 'SearchSploit'],
            concepts: ['Staged vs Non-staged Payloads', 'Port Pivoting / SOCKS Proxy', 'Meterpreter Post-Exploitation', 'Buffer Overflow Basics'],
            projectIdea: 'Gain root shell access on an unpatched Windows/Linux target machine in an isolated lab.',
            isPopular: true,
          },
          {
            id: 'sec-priv-esc',
            title: 'Linux & Windows Privilege Escalation',
            description: 'Enumerate misconfigured sudo rules, kernel exploits, vulnerable services, and unquoted service paths.',
            category: 'Offensive Security',
            level: 'Advanced',
            estimatedHours: 28,
            tools: ['LinPEAS', 'WinPEAS', 'BloodHound'],
            concepts: ['Sudo Abuse Rights', 'Kernel Exploitation Risk', 'Token Impersonation', 'Path Traversal Escalation'],
            projectIdea: 'Escalate from low-privilege www-data user to root using LinPEAS findings on HackTheBox.',
          },
        ],
      },
      {
        id: 'sec-p4',
        title: 'Defensive Security: SOC, SIEM & Threat Hunting',
        tagline: 'Log aggregation, IDS/IPS alerts, memory forensics, and incident response playbook execution.',
        iconName: 'Eye',
        phaseNumber: 4,
        estimatedWeeks: 5,
        nodes: [
          {
            id: 'sec-siem-splunk',
            title: 'SIEM Log Analysis with Splunk & ELK',
            description: 'Ingest Syslog, Windows Event Logs (Sysmon), craft SPL search queries, and build alert dashboards.',
            category: 'Defensive SOC',
            level: 'Intermediate',
            estimatedHours: 26,
            tools: ['Splunk Enterprise', 'Elasticsearch / Kibana', 'Sysmon'],
            concepts: ['SPL Search Processing', 'Correlation Rules', 'Brute Force Detection', 'Command Line Telemetry'],
            projectIdea: 'Configure Splunk to detect Pass-the-Hash and RDP brute-force attacks from Windows event logs.',
            isPopular: true,
          },
          {
            id: 'sec-incident-response',
            title: 'Incident Response & Digital Forensics',
            description: 'The 6 phases of incident response, volatility memory analysis, disk image acquisition, and IOC extraction.',
            category: 'Forensics',
            level: 'Advanced',
            estimatedHours: 22,
            tools: ['Volatility 3', 'Autopsy', 'FTK Imager'],
            concepts: ['Volatile Memory Dumping', 'Malware Process Injection Detection', 'Timeline Analysis', 'YARA Rules'],
            projectIdea: 'Analyze a memory dump from an infected host to extract C2 server IP and injected malware DLL.',
          },
        ],
      },
      {
        id: 'sec-p5',
        title: 'Certifications & Professional Career Lab',
        tagline: 'CEH, CompTIA Security+, OSCP preparation, and professional penetration test report writing.',
        iconName: 'Award',
        phaseNumber: 5,
        estimatedWeeks: 4,
        nodes: [
          {
            id: 'sec-pentest-reporting',
            title: 'Professional Pen Test Reporting & CVSS',
            description: 'Structure executive summaries, technical vulnerability proofs of concept, CVSS v3.1 scoring, and remediation roadmaps.',
            category: 'Professional Practice',
            level: 'Expert',
            estimatedHours: 20,
            tools: ['CVSS Calculator', 'Markdown / LaTeX', 'GitHub'],
            concepts: ['Risk Assessment', 'Executive Communication', 'Remediation Verification', 'Scope & Legal ROE'],
            projectIdea: 'Write a full 20-page simulated corporate penetration testing report suitable for board presentation.',
            isPopular: true,
          },
        ],
      },
    ],
    milestones: [
      {
        phase: 1,
        title: 'Linux & Network Foundations',
        duration: 'Month 1',
        level: 'Beginner',
        description: 'Understand packet transport, network architectures, and master command-line Linux administration.',
        deliverable: 'Complete capture-the-flag network challenges and deploy a hardened cloud firewall.',
        keySkills: ['Wireshark Inspection', 'TCP/IP Analysis', 'Linux CLI Hardening', 'Bash Scripting'],
        checkpointProjects: ['Network Reconnaissance Scanner Script', 'VPS Security Hardening Audit'],
      },
      {
        phase: 2,
        title: 'Web Application Hacking',
        duration: 'Month 2-3',
        level: 'Intermediate',
        description: 'Identify and exploit OWASP Top 10 vulnerabilities in modern web applications and APIs.',
        deliverable: 'Identify 10+ distinct vulnerabilities in target test environments with validated exploits.',
        keySkills: ['Burp Suite Proxy', 'SQL Injection (SQLi)', 'Cross-Site Scripting (XSS)', 'IDOR & BOLA'],
        checkpointProjects: ['DVWA Lab Exploit Suite', 'Custom Subdomain & Vulnerability Fuzzer'],
      },
      {
        phase: 3,
        title: 'Exploitation & Lateral Movement',
        duration: 'Month 4',
        level: 'Advanced',
        description: 'Leverage exploit frameworks, escalate system privileges, and pivot across internal subnets.',
        deliverable: 'Root access achieved across 5 intermediate HackTheBox / TryHackMe vulnerable virtual machines.',
        keySkills: ['Metasploit Framework', 'Privilege Escalation', 'Port Forwarding', 'Shellcraft'],
        checkpointProjects: ['Custom Reverse Shell Generator', 'Privilege Escalation Enum Tool'],
      },
      {
        phase: 4,
        title: 'SOC Monitoring & Forensics',
        duration: 'Month 5-6',
        level: 'Advanced',
        description: 'Construct security operations telemetry, investigate suspicious activity, and trace intrusions.',
        deliverable: 'A live Splunk monitoring dashboard alerting on simulated adversary attack sequences.',
        keySkills: ['Splunk SPL', 'Sysmon Event Logs', 'Memory Forensics (Volatility)', 'Incident Triage'],
        checkpointProjects: ['SOC Detection Pipeline', 'Ransomware Infection Post-Mortem'],
      },
      {
        phase: 5,
        title: 'Certification & Audit Capstone',
        duration: 'Month 7',
        level: 'Capstone',
        description: 'Conduct a simulated enterprise infrastructure penetration test and author an industry-grade audit report.',
        deliverable: 'Comprehensive Security Audit Report with CVSS risk metrics and technical executive briefing.',
        keySkills: ['Audit Methodology', 'CVSS v3.1 Scoring', 'Remediation Advisory', 'OSCP Exam Readiness'],
        checkpointProjects: ['Enterprise Infrastructure Pentest Portfolio'],
      },
    ],
    relatedCourses: ['course-1', 'course-2'],
    relatedTools: ['tool-wireshark', 'tool-burp-suite', 'tool-git'],
    relatedNotes: ['notes-cyber-sec', 'notes-devops-cheatsheet', 'notes-python-handbook'],
  },

  // ── 3. CLOUD ENGINEERING & DEVOPS / SRE ───────────────────────────────────
  {
    id: 'cloud-devops',
    title: 'Cloud Architect & DevOps SRE',
    category: 'cloud',
    categoryLabel: 'Cloud & DevOps',
    tagline: 'Infrastructure as Code (Terraform), Kubernetes cluster orchestration, GitOps, CI/CD, and 99.99% high availability.',
    description: 'Master multi-cloud provisioning and modern site reliability engineering. Transform manual operations into declarative Terraform infrastructure, Dockerize microservices, deploy auto-scaling Kubernetes clusters, establish automated GitHub Actions pipelines, and monitor telemetry with Prometheus and Grafana.',
    iconName: 'CloudCog',
    difficulty: 'Intermediate',
    duration: '6 Months',
    weeklyCommitment: '10-12 hrs/week',
    totalTopics: 26,
    salaryBenchmark: '₹16 LPA - ₹50 LPA / $120k - $195k',
    badgeColor: 'amber',
    accentGradient: 'from-amber-500 via-orange-600 to-emerald-500',
    careerRoles: ['DevOps Engineer', 'Cloud Solutions Architect', 'Site Reliability Engineer (SRE)', 'Platform Engineer'],
    overviewStats: {
      phasesCount: 5,
      projectsCount: 6,
      estimatedTotalHours: 230,
    },
    mindtree: [
      {
        id: 'cloud-p1',
        title: 'Linux Systems & Container Runtimes',
        tagline: 'Namespaces, cgroups, Docker daemon, container registries, and networking.',
        iconName: 'Server',
        phaseNumber: 1,
        estimatedWeeks: 4,
        nodes: [
          {
            id: 'cloud-docker-deep',
            title: 'Docker Internals & Compose Orchestration',
            description: 'Understand Linux namespaces, layered file systems, volume persistence, and multi-service networking.',
            category: 'Containers',
            level: 'Beginner',
            estimatedHours: 20,
            tools: ['Docker', 'Docker Compose', 'Alpine Linux'],
            concepts: ['cgroups & Namespaces', 'Image Optimization', 'Bridge Networks', 'Volume Bind Mounts'],
            projectIdea: 'Build a multi-container stack with NGINX reverse proxy, Node API, and PostgreSQL with persistent volumes.',
            isPopular: true,
          },
          {
            id: 'cloud-bash-scripting',
            title: 'Bash Automation & Linux Admin',
            description: 'Systemd service unit files, automated cron maintenance, SSH tunneling, and shell text processing (grep, sed, awk).',
            category: 'System Admin',
            level: 'Beginner',
            estimatedHours: 16,
            tools: ['Bash', 'systemd', 'cron', 'curl'],
            concepts: ['Exit Codes & Traps', 'Process Supervision', 'Pipes & Redirection', 'Automated Health Monitors'],
            projectIdea: 'Write a self-healing Linux service monitor script that restarts crashed services and sends Telegram alerts.',
          },
        ],
      },
      {
        id: 'cloud-p2',
        title: 'Infrastructure as Code (IaC) with Terraform',
        tagline: 'Declarative state management, cloud modules, variables, and automated drift detection.',
        iconName: 'Code',
        phaseNumber: 2,
        estimatedWeeks: 5,
        nodes: [
          {
            id: 'cloud-terraform',
            title: 'Terraform State & Multi-Cloud Modules',
            description: 'Declarative HCL syntax, S3 remote state storage with DynamoDB locking, and reusable VPC/VM modules.',
            category: 'IaC',
            level: 'Intermediate',
            estimatedHours: 28,
            tools: ['Terraform', 'TFLint', 'AWS CLI'],
            concepts: ['State Locking', 'Terraform Plan & Apply', 'Dynamic Blocks', 'Secrets Management in IaC'],
            projectIdea: 'Provision a production-ready AWS VPC with public/private subnets, NAT Gateway, and EC2 auto-scaling group.',
            isPopular: true,
          },
          {
            id: 'cloud-aws-core',
            title: 'AWS Core Services (VPC, IAM, S3, RDS)',
            description: 'IAM least-privilege security policies, VPC peering, Route 53 DNS, S3 lifecycle rules, and managed RDS.',
            category: 'Cloud Providers',
            level: 'Intermediate',
            estimatedHours: 30,
            tools: ['AWS Console', 'AWS CLI', 'LocalStack'],
            concepts: ['IAM Role Assumption', 'Security Groups vs NACLs', 'Load Balancers (ALB)', 'CloudWatch Metrics'],
            projectIdea: 'Deploy a resilient serverless web backend using AWS Lambda, API Gateway, DynamoDB, and CloudFront.',
          },
        ],
      },
      {
        id: 'cloud-p3',
        title: 'Kubernetes (K8s) Cluster Architecture',
        tagline: 'Pods, Deployments, StatefulSets, Services, Ingress, and Helm charts.',
        iconName: 'Cpu',
        phaseNumber: 3,
        estimatedWeeks: 6,
        nodes: [
          {
            id: 'cloud-k8s-core',
            title: 'Kubernetes Pods, Deployments & Services',
            description: 'Master control plane mechanics (kube-apiserver, etcd, scheduler), replica sets, and cluster IP routing.',
            category: 'Container Orchestration',
            level: 'Advanced',
            estimatedHours: 35,
            tools: ['kubectl', 'Minikube / k3s', 'Helm', 'K9s'],
            concepts: ['Pod Lifecycle & Probes', 'ClusterIP / NodePort / LoadBalancer', 'ConfigMaps & Secrets', 'Horizontal Pod Autoscaler (HPA)'],
            projectIdea: 'Deploy an auto-scaling multi-tier application to a k3s cluster with automated readiness/liveness health checks.',
            isPopular: true,
          },
          {
            id: 'cloud-helm-packaging',
            title: 'Helm Package Management & Templating',
            description: 'Write production Helm charts, values overrides for staging/prod environments, and chart dependencies.',
            category: 'Orchestration Tooling',
            level: 'Intermediate',
            estimatedHours: 18,
            tools: ['Helm 3', 'Artifact Hub'],
            concepts: ['Chart Architecture', 'Go Templates in Helm', 'Release Rollbacks', 'Sub-charts'],
            projectIdea: 'Package a custom web stack into a production Helm chart with configurable replica and resource requests.',
          },
        ],
      },
      {
        id: 'cloud-p4',
        title: 'GitOps, CI/CD & Automated Observability',
        tagline: 'GitHub Actions, ArgoCD declarative deployments, Prometheus metrics, and Grafana dashboards.',
        iconName: 'Activity',
        phaseNumber: 4,
        estimatedWeeks: 5,
        nodes: [
          {
            id: 'cloud-cicd-github',
            title: 'GitHub Actions CI/CD Automation',
            description: 'Build automated test suites, linting matrices, Docker image publishing to GHCR, and automated release tags.',
            category: 'Continuous Integration',
            level: 'Intermediate',
            estimatedHours: 22,
            tools: ['GitHub Actions', 'Docker Buildx', 'Semantic Release'],
            concepts: ['Pipeline Matrix Strategy', 'Environment Secrets & OIDC', 'Artifact Caching', 'Self-Hosted Runners'],
            projectIdea: 'Create an automated pipeline that builds, tests, scans with Trivy, and pushes Docker images to GHCR.',
            isPopular: true,
          },
          {
            id: 'cloud-argocd-gitops',
            title: 'GitOps Continuous Delivery with ArgoCD',
            description: 'Declarative cluster state sync, automated self-healing, canary deployments, and rollback automation.',
            category: 'Continuous Delivery',
            level: 'Advanced',
            estimatedHours: 20,
            tools: ['ArgoCD', 'GitOps Repositories'],
            concepts: ['Reconciliation Loops', 'Sync Policies', 'Drift Detection', 'Canary Rollouts with Argo Rollouts'],
            projectIdea: 'Configure an ArgoCD GitOps pipeline that syncs application updates automatically on git push.',
          },
          {
            id: 'cloud-observability',
            title: 'Prometheus & Grafana Observability',
            description: 'Scrape metrics, configure Alertmanager triggers, design custom Grafana dashboards, and track SLOs.',
            category: 'Site Reliability',
            level: 'Advanced',
            estimatedHours: 24,
            tools: ['Prometheus', 'Grafana', 'Alertmanager', 'Loki'],
            concepts: ['PromQL Queries', 'Golden Signals (Latency, Traffic, Errors, Saturation)', 'SLO/SLI Error Budgets', 'Alert Rules'],
            projectIdea: 'Deploy a complete monitoring stack that triggers Discord/Slack alerts when HTTP 5xx errors exceed 1%.',
            isPopular: true,
          },
        ],
      },
    ],
    milestones: [
      {
        phase: 1,
        title: 'Containerization & Shell Foundations',
        duration: 'Month 1',
        level: 'Beginner',
        description: 'Package software into standardized containers and master Linux system automation scripts.',
        deliverable: 'A multi-container application orchestrated with health checks and volume persistence.',
        keySkills: ['Docker Multi-Stage', 'Compose Stacks', 'Bash Automation', 'Linux Permissions'],
        checkpointProjects: ['Microservice Container Suite', 'Automated Database Backup Bot'],
      },
      {
        phase: 2,
        title: 'Cloud Architecture & Infrastructure as Code',
        duration: 'Month 2-3',
        level: 'Intermediate',
        description: 'Model scalable cloud infrastructure using declarative Terraform code on AWS.',
        deliverable: 'Complete AWS cloud topology provisioned purely via code with state locking.',
        keySkills: ['Terraform Modules', 'AWS VPC & Subnets', 'IAM Least Privilege', 'Cloud Storage S3'],
        checkpointProjects: ['Production AWS Terraform Topology', 'Serverless Backend API'],
      },
      {
        phase: 3,
        title: 'Kubernetes Orchestration & Helm',
        duration: 'Month 4',
        level: 'Advanced',
        description: 'Deploy, scale, and manage stateful and stateless applications inside production Kubernetes clusters.',
        deliverable: 'Auto-scaling cluster running behind NGINX ingress with zero-downtime rolling updates.',
        keySkills: ['Kubernetes Manifests', 'Ingress Controllers', 'Helm Chart Packaging', 'Cluster Scaling'],
        checkpointProjects: ['High-Availability K8s Cluster Deployment'],
      },
      {
        phase: 4,
        title: 'GitOps CI/CD & Observability',
        duration: 'Month 5-6',
        level: 'Advanced',
        description: 'Establish automated continuous delivery using ArgoCD and observe cluster health with Prometheus.',
        deliverable: 'Automated CI/CD pipeline connecting Git commits directly to cluster deployments with live Grafana metrics.',
        keySkills: ['GitHub Actions Workflows', 'ArgoCD GitOps Sync', 'PromQL Queries', 'Grafana Dashboards'],
        checkpointProjects: ['End-to-End GitOps Continuous Delivery Platform'],
      },
    ],
    relatedCourses: ['course-3', 'course-1'],
    relatedTools: ['tool-docker-desktop', 'tool-git', 'tool-vscode'],
    relatedNotes: ['notes-devops-cheatsheet', 'notes-cyber-sec', 'notes-python-handbook'],
  },

  // ── 4. PYTHON AUTOMATION & WORKFLOW ENGINEERING ───────────────────────────
  {
    id: 'python-automation',
    title: 'Python Automation & Workflow Engineer',
    category: 'automation',
    categoryLabel: 'Automation & Scripting',
    tagline: 'Headless browser bots (Playwright), web scrapers, spreadsheet ETL, automated APIs, and scheduled AI workflows.',
    description: 'Transform manual, repetitive daily tasks into reliable autonomous code. Master Python scripting, file system processing, automated web scrapers with BeautifulSoup & Playwright, REST API bots, Excel & PDF batch processing, cron jobs, and integrating LLMs for intelligent workflow automation.',
    iconName: 'Zap',
    difficulty: 'Beginner',
    duration: '4 Months',
    weeklyCommitment: '8-10 hrs/week',
    totalTopics: 22,
    salaryBenchmark: '₹10 LPA - ₹32 LPA / $85k - $150k',
    badgeColor: 'emerald',
    accentGradient: 'from-emerald-600 via-teal-600 to-blue-500',
    careerRoles: ['Automation Engineer', 'Python Developer', 'Data Operations Specialist', 'RPA Developer'],
    overviewStats: {
      phasesCount: 4,
      projectsCount: 5,
      estimatedTotalHours: 160,
    },
    mindtree: [
      {
        id: 'auto-p1',
        title: 'Python Scripting & File System Mastery',
        tagline: 'Pathlib file operations, regex parsing, CSV/JSON processing, and error handling.',
        iconName: 'FileCode',
        phaseNumber: 1,
        estimatedWeeks: 3,
        nodes: [
          {
            id: 'auto-python-core',
            title: 'Modern Python 3.12 Idiomatic Code',
            description: 'List comprehensions, generators, context managers, dataclasses, and robust try/except error handling.',
            category: 'Python Foundations',
            level: 'Beginner',
            estimatedHours: 16,
            tools: ['Python 3.12', 'UV / Poetry', 'Ruff'],
            concepts: ['Context Managers (with)', 'Generators & Memory Efficiency', 'Dataclasses', 'Type Hints'],
            projectIdea: 'Build a bulk directory organizer that renames, tags, and sorts thousands of messy files by metadata.',
            isPopular: true,
          },
          {
            id: 'auto-data-processing',
            title: 'Excel, PDF & CSV Batch Processing',
            description: 'Automate data extraction from messy PDFs, format Excel sheets with formulas, and merge huge CSV datasets.',
            category: 'Document Automation',
            level: 'Beginner',
            estimatedHours: 18,
            tools: ['pandas', 'openpyxl', 'pypdf', 'pdfplumber'],
            concepts: ['DataFrame Manipulation', 'Cell Formatting', 'Text & Table Extraction from PDF', 'Batch File Merging'],
            projectIdea: 'Automate generation of weekly sales PDF invoices with charts from raw CSV spreadsheets.',
          },
        ],
      },
      {
        id: 'auto-p2',
        title: 'Web Scraping & Browser Automation',
        tagline: 'Headless browsers, bypass bot protection, extract dynamic SPA data, and simulate user actions.',
        iconName: 'Bot',
        phaseNumber: 2,
        estimatedWeeks: 4,
        nodes: [
          {
            id: 'auto-playwright',
            title: 'Headless Browser Automation with Playwright',
            description: 'Automate dynamic JavaScript single-page apps, take screenshots, fill complex forms, and intercept network requests.',
            category: 'Web Automation',
            level: 'Intermediate',
            estimatedHours: 24,
            tools: ['Playwright Python', 'pytest-playwright'],
            concepts: ['Async Selectors', 'Network Interception', 'Authentication State Storage', 'Headless vs Headed Mode'],
            projectIdea: 'Build an automated price-tracking bot that logs into an e-commerce site and alerts on price drops.',
            isPopular: true,
          },
          {
            id: 'auto-scraping-bs4',
            title: 'High-Speed Web Scraping (BeautifulSoup & Scrapy)',
            description: 'Fast HTML parsing, multi-threaded request pools, user-agent rotation, and structured JSON extraction.',
            category: 'Scraping',
            level: 'Intermediate',
            estimatedHours: 20,
            tools: ['BeautifulSoup4', 'httpx', 'Scrapy'],
            concepts: ['CSS Selectors & XPath', 'Rate Limiting & Delays', 'Proxy Pools', 'HTML Sanitization'],
            projectIdea: 'Scrape tech job boards daily, filter by salary and skills, and email a curated digest.',
          },
        ],
      },
      {
        id: 'auto-p3',
        title: 'API Automation & Notification Bots',
        tagline: 'REST integrations, Telegram/WhatsApp bots, scheduled cron jobs, and webhook listeners.',
        iconName: 'Send',
        phaseNumber: 3,
        estimatedWeeks: 4,
        nodes: [
          {
            id: 'auto-telegram-discord',
            title: 'Telegram, Discord & WhatsApp Chatbots',
            description: 'Create interactive bots that accept user commands, generate reports, and push urgent notifications.',
            category: 'Notification Bots',
            level: 'Intermediate',
            estimatedHours: 18,
            tools: ['python-telegram-bot', 'discord.py', 'Twilio API'],
            concepts: ['Webhook Handlers', 'Command Handlers', 'Polling vs Webhook Events', 'Inline Buttons'],
            projectIdea: 'Build a server monitoring Telegram bot that responds to /status, /restart, and /logs commands.',
            isPopular: true,
          },
          {
            id: 'auto-scheduling-cron',
            title: 'Task Scheduling & Cloud Cron Jobs',
            description: 'Schedule automated scripts to run reliably 24/7 on Linux cron, Celery, or GitHub Actions scheduled workflows.',
            category: 'Job Scheduling',
            level: 'Intermediate',
            estimatedHours: 15,
            tools: ['APScheduler', 'cron', 'GitHub Actions Cron'],
            concepts: ['Cron Syntax', 'Daemon Processes', 'Failure Retry Logic', 'Job Logging'],
            projectIdea: 'Deploy a serverless scheduled bot that generates daily cryptocurrency market summaries.',
          },
        ],
      },
      {
        id: 'auto-p4',
        title: 'AI-Powered Agentic Workflows',
        tagline: 'Integrating OpenAI / Gemini API into automation scripts for document summary, OCR, and smart sorting.',
        iconName: 'Sparkles',
        phaseNumber: 4,
        estimatedWeeks: 4,
        nodes: [
          {
            id: 'auto-llm-workflows',
            title: 'LLM Agentic Tool-Calling Automations',
            description: 'Connect Gemini / OpenAI APIs with local Python functions to execute automated multi-step research and data cleanup.',
            category: 'AI Automation',
            level: 'Advanced',
            estimatedHours: 25,
            tools: ['Google GenAI SDK', 'OpenAI Python', 'LangChain'],
            concepts: ['Function Calling / Tool Use', 'Structured JSON Outputs', 'Autonomous Loops', 'Prompt Engineering for Scripts'],
            projectIdea: 'Build an autonomous research agent that searches the web, summarizes 10 articles, and formats an executive PDF report.',
            isPopular: true,
          },
        ],
      },
    ],
    milestones: [
      {
        phase: 1,
        title: 'Python Scripting & Document Processing',
        duration: 'Month 1',
        level: 'Beginner',
        description: 'Master core Python mechanics, file handling, and batch operations across Excel, CSV, and PDF files.',
        deliverable: 'A suite of 5 practical file-management and invoice-generation scripts.',
        keySkills: ['Python 3.12 Syntax', 'Pathlib Automation', 'pandas DataFrame ETL', 'PDF Extraction'],
        checkpointProjects: ['Automated File Classifier', 'Excel Report Formatter'],
      },
      {
        phase: 2,
        title: 'Web Scraping & Browser Bots',
        duration: 'Month 2',
        level: 'Intermediate',
        description: 'Build robust web scrapers and control real browsers programmatically using Playwright.',
        deliverable: 'Autonomous browser bot capable of navigating logins, solving forms, and scraping dynamic SPAs.',
        keySkills: ['Playwright Automation', 'BeautifulSoup4 Selectors', 'Network Mocking', 'Anti-Detection Practices'],
        checkpointProjects: ['E-Commerce Price Tracker', 'Lead Generation Scraper'],
      },
      {
        phase: 3,
        title: 'Messaging Bots & Scheduled Cloud Tasks',
        duration: 'Month 3',
        level: 'Intermediate',
        description: 'Connect scripts to external APIs, build Telegram/Discord notification bots, and schedule them 24/7.',
        deliverable: 'A live Telegram bot deployed on a cloud server running automated daily scheduled tasks.',
        keySkills: ['REST API Integrations', 'Telegram Bot API', 'APScheduler', 'Linux Cron Jobs'],
        checkpointProjects: ['System Health Telegram Bot', 'Daily Crypto & Stock Digest'],
      },
      {
        phase: 4,
        title: 'Intelligent AI-Powered Automation',
        duration: 'Month 4',
        level: 'Advanced',
        description: 'Combine browser automation with Large Language Model APIs for autonomous research and data summarization.',
        deliverable: 'End-to-end intelligent agent that crawls target websites, analyzes content with AI, and generates reports.',
        keySkills: ['LLM Function Calling', 'Structured JSON Extraction', 'Autonomous Agent Loops', 'End-to-End Delivery'],
        checkpointProjects: ['Autonomous Market Intelligence Agent'],
      },
    ],
    relatedCourses: ['course-2', 'course-1'],
    relatedTools: ['tool-python', 'tool-vscode', 'tool-git'],
    relatedNotes: ['notes-python-handbook', 'notes-devops-cheatsheet', 'notes-fullstack-dev'],
  },

  // ── 5. ARTIFICIAL INTELLIGENCE & LLM SYSTEMS ──────────────────────────────
  {
    id: 'ai-llm',
    title: 'Generative AI & LLM Systems Engineer',
    category: 'ai',
    categoryLabel: 'Artificial Intelligence',
    tagline: 'Transformer architectures, PyTorch deep learning, RAG pipelines with vector DBs, LoRA fine-tuning, and production inference.',
    description: 'Go beyond basic API prompting. Understand modern generative AI from foundational tensor math and attention mechanisms to production-scale retrieval augmented generation (RAG), vector embeddings, parameter-efficient fine-tuning (PEFT / LoRA), and deploying optimized inference servers with vLLM.',
    iconName: 'BrainCircuit',
    difficulty: 'Advanced',
    duration: '8 Months',
    weeklyCommitment: '12-14 hrs/week',
    totalTopics: 28,
    salaryBenchmark: '₹18 LPA - ₹65 LPA / $130k - $240k',
    badgeColor: 'purple',
    accentGradient: 'from-purple-600 via-pink-600 to-indigo-500',
    careerRoles: ['AI Application Engineer', 'LLM Systems Architect', 'Machine Learning Engineer', 'GenAI Research Engineer'],
    overviewStats: {
      phasesCount: 4,
      projectsCount: 6,
      estimatedTotalHours: 300,
    },
    mindtree: [
      {
        id: 'ai-p1',
        title: 'Deep Learning Primitives & PyTorch',
        tagline: 'Tensors, autograd, forward/backward passes, and neural network architectures.',
        iconName: 'Cpu',
        phaseNumber: 1,
        estimatedWeeks: 6,
        nodes: [
          {
            id: 'ai-pytorch-core',
            title: 'PyTorch Tensors, Autograd & GPU Acceleration',
            description: 'Master tensor shapes, gradient computation with backward(), CUDA GPU acceleration, and writing custom nn.Module classes.',
            category: 'Deep Learning',
            level: 'Beginner',
            estimatedHours: 30,
            tools: ['PyTorch 2.x', 'CUDA Toolkit', 'NumPy'],
            concepts: ['Autograd Engine', 'Tensor Broadcasting', 'Loss Functions & Optimizers (AdamW)', 'Batch Processing'],
            projectIdea: 'Implement a neural network classifier from scratch in PyTorch to classify handwritten digits.',
            isPopular: true,
          },
          {
            id: 'ai-embeddings',
            title: 'Vector Embeddings & Semantic Search',
            description: 'Word2Vec, sentence transformers, cosine similarity metrics, and high-dimensional vector representations.',
            category: 'Embeddings',
            level: 'Intermediate',
            estimatedHours: 20,
            tools: ['sentence-transformers', 'Hugging Face Hub'],
            concepts: ['Cosine Similarity', 'Vector Normalization', 'Dimensionality Reduction', 'Semantic Clustering'],
            projectIdea: 'Build a semantic document search engine comparing 10,000 research abstracts.',
          },
        ],
      },
      {
        id: 'ai-p2',
        title: 'Transformer Architecture & Attention Mechanisms',
        tagline: 'Multi-Head Attention, positional encodings, self-attention math, and tokenizer algorithms.',
        iconName: 'Boxes',
        phaseNumber: 2,
        estimatedWeeks: 7,
        nodes: [
          {
            id: 'ai-attention-math',
            title: 'Self-Attention & Transformer Coding from Scratch',
            description: 'Code Scaled Dot-Product Attention: Softmax(QK^T / sqrt(d_k))V, multi-head projections, and causal masking.',
            category: 'Architecture',
            level: 'Advanced',
            estimatedHours: 35,
            tools: ['PyTorch', 'Jupyter Notebook'],
            concepts: ['Query-Key-Value Projections', 'Causal Attention Masks', 'LayerNorm & Residuals', 'Feed-Forward Blocks'],
            projectIdea: 'Build and train a mini GPT language model from scratch on Shakespeare text.',
            isPopular: true,
          },
          {
            id: 'ai-tokenizers',
            title: 'Tokenization Algorithms (BPE & WordPiece)',
            description: 'Byte-Pair Encoding, vocabulary construction, token IDs, attention masks, and context window limits.',
            category: 'NLP',
            level: 'Intermediate',
            estimatedHours: 18,
            tools: ['HuggingFace Tokenizers', 'TikToken'],
            concepts: ['BPE Merge Rules', 'Special Tokens ([CLS], [SEP])', 'Out-of-Vocabulary Mitigation', 'Token-to-Cost Calculations'],
            projectIdea: 'Train a custom Byte-Pair Encoding tokenizer on multilingual technical documentation.',
          },
        ],
      },
      {
        id: 'ai-p3',
        title: 'Production RAG & Vector Databases',
        tagline: 'Chunking strategies, hybrid vector + keyword search, re-ranking, and hallucination reduction.',
        iconName: 'Database',
        phaseNumber: 3,
        estimatedWeeks: 6,
        nodes: [
          {
            id: 'ai-vector-databases',
            title: 'Vector Databases (Qdrant, Pinecone, pgvector)',
            description: 'HNSW indexing algorithms, metadata filtering, hybrid search with BM25, and vector indexing benchmarks.',
            category: 'Vector DBs',
            level: 'Intermediate',
            estimatedHours: 26,
            tools: ['pgvector', 'Qdrant', 'Pinecone'],
            concepts: ['HNSW vs Flat Index', 'Metadata Filtering', 'Hybrid Search', 'Multi-tenant Vector Collections'],
            projectIdea: 'Deploy a pgvector relational database storing millions of company code snippets with sub-20ms search.',
            isPopular: true,
          },
          {
            id: 'ai-advanced-rag',
            title: 'Advanced RAG: Chunking, Re-Ranking & Guardrails',
            description: 'Semantic chunking, cross-encoder re-rankers (Cohere), contextual compression, and NeMo guardrails.',
            category: 'RAG Architecture',
            level: 'Advanced',
            estimatedHours: 32,
            tools: ['LlamaIndex', 'LangChain', 'Cohere Rerank', 'NeMo Guardrails'],
            concepts: ['Semantic Chunk Splitting', 'Cross-Encoder Re-Ranking', 'Hallucination Mitigation', 'Evaluation with Ragas'],
            projectIdea: 'Build an enterprise technical documentation assistant with Ragas evaluation scoring 90%+ faithfulness.',
            isPopular: true,
          },
        ],
      },
      {
        id: 'ai-p4',
        title: 'Model Fine-Tuning, vLLM & Production Serving',
        tagline: 'LoRA, QLoRA, quantization (GGUF, AWQ), high-throughput vLLM serving, and agentic orchestration.',
        iconName: 'Cpu',
        phaseNumber: 4,
        estimatedWeeks: 6,
        nodes: [
          {
            id: 'ai-lora-fine-tuning',
            title: 'PEFT & QLoRA Fine-Tuning',
            description: 'Low-Rank Adaptation (LoRA), 4-bit quantization (BitsAndBytes), instruction dataset prep, and loss tracking.',
            category: 'Fine-Tuning',
            level: 'Expert',
            estimatedHours: 35,
            tools: ['Unsloth', 'PEFT', 'Hugging Face SFTTrainer', 'Weights & Biases'],
            concepts: ['Rank & Alpha Hyperparameters', 'Low-Rank Decomposition', 'Dataset Curation', 'Validation Loss Curves'],
            projectIdea: 'Fine-tune a Llama-3-8B model on specialized legal/medical contracts using consumer GPU compute.',
            isPopular: true,
          },
          {
            id: 'ai-vllm-serving',
            title: 'High-Throughput Inference with vLLM',
            description: 'PagedAttention memory management, continuous batching, tensor parallelism, and OpenAI-compatible API serving.',
            category: 'Inference Serving',
            level: 'Expert',
            estimatedHours: 25,
            tools: ['vLLM', 'TGI', 'Ollama', 'Docker'],
            concepts: ['PagedAttention Internals', 'Continuous Batching', 'Time to First Token (TTFT)', 'Tokens per Second (TPS)'],
            projectIdea: 'Deploy an auto-scaling private LLM inference cluster on cloud GPUs capable of serving 50 concurrent streams.',
            isPopular: true,
          },
        ],
      },
    ],
    milestones: [
      {
        phase: 1,
        title: 'PyTorch & Mathematical Foundations',
        duration: 'Month 1-2',
        level: 'Beginner',
        description: 'Master tensor manipulations, backpropagation, and semantic vector embeddings.',
        deliverable: 'Custom neural network and embedding search engine built natively in PyTorch.',
        keySkills: ['PyTorch Tensors', 'Autograd Engine', 'Vector Math', 'Semantic Embeddings'],
        checkpointProjects: ['Neural Network from Scratch', 'Semantic Document Clusterer'],
      },
      {
        phase: 2,
        title: 'Transformer Architecture Mastery',
        duration: 'Month 3-4',
        level: 'Intermediate',
        description: 'Understand and code the multi-head self-attention mechanism and causal transformer blocks.',
        deliverable: 'A working mini-GPT model trained from scratch with text generation capabilities.',
        keySkills: ['Scaled Dot-Product Attention', 'Byte-Pair Encoding', 'Layer Normalization', 'Causal Masking'],
        checkpointProjects: ['Mini-GPT Architecture', 'Custom BPE Tokenizer'],
      },
      {
        phase: 3,
        title: 'Production RAG & Vector Databases',
        duration: 'Month 5-6',
        level: 'Advanced',
        description: 'Design and deploy production-grade retrieval augmented generation systems with evaluation telemetry.',
        deliverable: 'Enterprise RAG application with hybrid vector search, cross-encoder re-ranking, and automated evaluation.',
        keySkills: ['pgvector & Qdrant', 'Semantic Chunking', 'Cross-Encoder Re-Ranking', 'Ragas Evaluation'],
        checkpointProjects: ['Enterprise Codebase RAG Assistant', 'Contract Analysis Agent'],
      },
      {
        phase: 4,
        title: 'Fine-Tuning & High-Throughput Serving',
        duration: 'Month 7-8',
        level: 'Capstone',
        description: 'Fine-tune open-weight models using QLoRA and deploy low-latency inference servers with vLLM.',
        deliverable: 'Fine-tuned domain model deployed with vLLM server behind a streaming web chat interface.',
        keySkills: ['QLoRA / PEFT', 'Dataset Instruction Formatting', 'vLLM PagedAttention', 'GPU Cluster Management'],
        checkpointProjects: ['Domain-Specific Fine-Tuned LLM', 'vLLM Production Inference Cluster'],
      },
    ],
    relatedCourses: ['course-2', 'course-3'],
    relatedTools: ['tool-python', 'tool-docker-desktop', 'tool-vscode'],
    relatedNotes: ['notes-python-handbook', 'notes-cyber-sec', 'notes-fullstack-dev'],
  },
];
